name: canary

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Module Info
        id: extract_info
        run: |
          MODULE_VERSION=$(grep -oP '^version=\K.*' module/module.prop)
          COMMIT_ID=$(git rev-parse --short HEAD)
          BUILD_COUNT=$((1000 + ${{ github.run_number }}))
          ARTIFACT_NAME="TrickyAddonModule-${MODULE_VERSION}-${COMMIT_ID}-canary-${BUILD_COUNT}"
          echo "MODULE_VERSION=${MODULE_VERSION}" >> $GITHUB_ENV
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: module/
